import 'package:paper_chat/models/paper.dart';

class MockPaperRepository {
  List<Paper> getAllPapers() {
    return _papers;
  }

  Paper? getPaperById(String id) {
    try {
      return _papers.firstWhere((p) => p.id == id);
    } catch (e) {
      return null;
    }
  }

  void addPaper(Paper paper) {
    _papers.insert(0, paper);
  }

  static final List<Paper> _papers = [
    Paper(
      id: 'attention',
      title: 'Attention Is All You Need',
      authors: ['Ashish Vaswani', 'Noam Shazeer', 'Niki Parmar', 'Jakob Uszkoreit'],
      year: 2017,
      abstractText: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.',
      tags: ['NLP', 'Transformer'],
      collection: 'Deep Learning',
      pages: [
        const PaperPage(
          pageNumber: 1,
          sectionTitle: 'Abstract and Introduction',
          content: 'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely.\n\nRecurrent neural networks, long short-term memory and gated recurrent neural networks in particular, have been firmly established as state of the art approaches in sequence modeling and transduction problems such as language modeling and machine translation. Numerous efforts have since continued to push the boundaries of recurrent language models and encoder-decoder architectures.\n\nAttention mechanisms have become an integral part of compelling sequence modeling and transduction models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences. In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output.',
        ),
        const PaperPage(
          pageNumber: 2,
          sectionTitle: 'Background',
          content: 'The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU, ByteNet and ConvS2S, all of which use convolutional neural networks as basic building block, computing hidden representations in parallel for all input and output positions. In these models, the number of operations required to relate signals from two arbitrary input or output positions grows in the distance between positions, linearly for ConvS2S and logarithmically for ByteNet. This makes it more difficult to learn dependencies between distant positions.\n\nIn the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention.\n\nSelf-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence. Self-attention has been used successfully in a variety of tasks including reading comprehension, abstractive summarization, textual entailment and learning task-independent sentence representations.',
        ),
        const PaperPage(
          pageNumber: 3,
          sectionTitle: 'Model Architecture',
          content: 'Most competitive neural sequence transduction models have an encoder-decoder structure. Here, the encoder maps an input sequence of symbol representations (x1, ..., xn) to a sequence of continuous representations z = (z1, ..., zn). Given z, the decoder then generates an output sequence (y1, ..., ym) of symbols one element at a time. At each step the model is auto-regressive, consuming the previously generated symbols as additional input when generating the next.\n\nThe Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively.\n\nThe encoder is composed of a stack of N=6 identical layers. Each layer has two sub-layers. The first is a multi-head self-attention mechanism, and the second is a simple, position-wise fully connected feed-forward network. We employ a residual connection around each of the two sub-layers, followed by layer normalization. That is, the output of each sub-layer is LayerNorm(x + Sublayer(x)), where Sublayer(x) is the function implemented by the sub-layer itself.',
        ),
        const PaperPage(
          pageNumber: 4,
          sectionTitle: 'Multi-Head Attention',
          content: 'An attention function can be described as mapping a query and a set of key-value pairs to an output, where the query, keys, values, and output are all vectors. The output is computed as a weighted sum of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key.\n\nWe call our particular attention "Scaled Dot-Product Attention". The input consists of queries and keys of dimension d_k, and values of dimension d_v. We compute the dot products of the query with all keys, divide each by sqrt(d_k), and apply a softmax function to obtain the weights on the values. In practice, we compute the attention function on a set of queries simultaneously, packed together into a matrix Q. The keys and values are also packed together into matrices K and V. We compute the matrix of outputs as: Attention(Q,K,V) = softmax(QK^T / sqrt(d_k))V.\n\nInstead of performing a single attention function with d_model-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values h times with different, learned linear projections to d_k, d_k and d_v dimensions, respectively. Attention is applied in parallel to these projected versions, yielding d_v-dimensional output values.',
        ),
        const PaperPage(
          pageNumber: 5,
          sectionTitle: 'Training and Results',
          content: 'We trained our models on one machine with 8 NVIDIA P100 GPUs. For our base models using the hyperparameters described throughout the paper, each training step took about 0.4 seconds. We trained the base models for a total of 100,000 steps or 12 hours. For our big models, step time was 1.0 seconds. The big models were trained for 300,000 steps (3.5 days).\n\nOn the WMT 2014 English-to-German translation task, the big transformer model (Transformer (big) in Table 2) outperforms the best previously reported models (including ensembles) by more than 2.0 BLEU, establishing a new state-of-the-art BLEU score of 28.4. The configuration of this model is described in the bottom line of Table 3. Training took 3.5 days on 8 P100 GPUs. Even our base model surpasses all previously published models and ensembles, at a fraction of the training cost of any of the competitive models.\n\nOn the WMT 2014 English-to-French translation task, our big model achieves a BLEU score of 41.0, outperforming all of the previously published single models, at less than 1/4 the training cost of the previous state-of-the-art model. The Transformer (big) model trained for English-to-French used dropout rate P_drop = 0.1, instead of 0.3.',
        ),
      ],
    ),
    Paper(
      id: 'gan',
      title: 'Generative Adversarial Networks',
      authors: ['Ian J. Goodfellow', 'Jean Pouget-Abadie', 'Mehdi Mirza', 'Bing Xu'],
      year: 2014,
      abstractText: 'We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model G that captures the data distribution, and a discriminative model D that estimates the probability that a sample came from the training data rather than G.',
      tags: ['Generative', 'GAN'],
      collection: 'Deep Learning',
      pages: [
        const PaperPage(
          pageNumber: 1,
          sectionTitle: 'Introduction',
          content: 'The promise of deep learning is to discover rich, hierarchical models that represent probability distributions over the kinds of data encountered in artificial intelligence applications, such as natural images, audio waveforms containing speech, and symbols in natural language corpora. So far, the most striking successes in deep learning have involved discriminative models, usually those that map a high-dimensional, rich sensory input to a class label. These striking successes have primarily been based on the backpropagation and dropout algorithms, using piecewise linear units which have a particularly well-behaved gradient.\n\nDeep generative models have had less of an impact, due to the difficulty of approximating many intractable probabilistic computations that arise in maximum likelihood estimation and related strategies, and due to difficulty of leveraging the benefits of piecewise linear units in the generative context. We propose a new generative model estimation procedure that sidesteps these difficulties.\n\nIn the proposed adversarial nets framework, the generative model is pitted against an adversary: a discriminative model that learns to determine whether a sample is from the model distribution or the data distribution. The generative model can be thought of as analogous to a team of counterfeiters, trying to produce fake currency and use it without detection, while the discriminative model is analogous to the police, trying to detect the counterfeit currency. Competition in this game drives both teams to improve their methods until the counterfeits are indistinguishable from the genuine articles.',
        ),
        const PaperPage(
          pageNumber: 2,
          sectionTitle: 'Adversarial Framework',
          content: 'To learn the generator\'s distribution p_g over data x, we define a prior on input noise variables p_z(z), then represent a mapping to data space as G(z; θ_g), where G is a differentiable function represented by a multilayer perceptron with parameters θ_g. We also define a second multilayer perceptron D(x; θ_d) that outputs a single scalar. D(x) represents the probability that x came from the data rather than p_g. We train D to maximize the probability of assigning the correct label to both training examples and samples from G.\n\nWe simultaneously train G to minimize log(1 - D(G(z))). In other words, D and G play the following two-player minimax game with value function V(G,D): min_G max_D V(D,G) = E_x~p_data(x)[log D(x)] + E_z~p_z(z)[log(1 - D(G(z)))].\n\nIn practice, this equation may not provide sufficient gradient for G to learn well. Early in learning, when G is poor, D can reject samples with high confidence because they are clearly different from the training data. In this case, log(1 - D(G(z))) saturates. Rather than training G to minimize log(1 - D(G(z))), we can train G to maximize log D(G(z)). This objective function results in the same fixed point of the dynamics of G and D but provides much stronger gradients early in learning.',
        ),
        const PaperPage(
          pageNumber: 3,
          sectionTitle: 'Theoretical Results',
          content: 'The generator G implicitly defines a probability distribution p_g as the distribution of the samples G(z) obtained when z ~ p_z. Therefore, we would like the algorithm to converge to a good estimator of p_data, if given enough capacity and training time. We consider the optimal discriminator D for any given generator G.\n\nFor G fixed, the optimal discriminator D_G* is D_G*(x) = p_data(x) / (p_data(x) + p_g(x)). This comes from the fact that the training criterion for the discriminator D, given any generator G, is to maximize the quantity V(G, D). By differentiating the integrand with respect to D(x) and setting it to zero, we arrive at the optimal discriminator.\n\nThe minimax game can now be reformulated as: C(G) = max_D V(G,D) = E_x~p_data[log D_G*(x)] + E_z~p_z[log(1 - D_G*(G(z)))]. We can show that the global minimum of the virtual training criterion C(G) is achieved if and only if p_g = p_data. At that point, the value of C(G) achieves the value of -log 4. In other words, the generative model perfectly replicates the data generating process, and the discriminator is completely unable to distinguish between real and generated samples, outputting 1/2 everywhere.',
        ),
        const PaperPage(
          pageNumber: 4,
          sectionTitle: 'Experiments',
          content: 'We trained adversarial nets an a range of datasets including MNIST, the Toronto Face Database (TFD), and CIFAR-10. The generator nets used a mixture of rectifier linear activations and sigmoid activations, while the discriminator net used maxout activations. Dropout was applied in training the discriminator net. While our theoretical framework permits the use of dropout and other noise at intermediate layers of the generator, we used noise as the input to only the bottommost layer of the generator network.\n\nWe estimate probability of the test set data under p_g by fitting a Gaussian Parzen window to the samples generated with G and reporting the log-likelihood under this distribution. The σ parameter of the Gaussians was obtained by cross validation on the validation set. This procedure was introduced in Breuleux et al. and used for various generative models for which the exact likelihood is not tractable. While this method of estimating the likelihood has high variance and does not perform well in high dimensional spaces, it is the best method available to our knowledge.\n\nImages generated by the model show that the generative model produces samples that appear at least competitive with the better generative models from the literature, although they lack quantitative evaluation metrics that definitively establish their superiority. The samples from the model show that it learns a representation that captures the underlying variations in the data.',
        ),
      ],
    ),
    Paper(
      id: 'resnet',
      title: 'Deep Residual Learning for Image Recognition',
      authors: ['Kaiming He', 'Xiangyu Zhang', 'Shaoqing Ren', 'Jian Sun'],
      year: 2015,
      abstractText: 'Deeper neural networks are more difficult to train. We present a residual learning framework to ease the training of networks that are substantially deeper than those used previously. We explicitly reformulate the layers as learning residual functions with reference to the layer inputs, instead of learning unreferenced functions.',
      tags: ['CNN', 'Computer Vision'],
      collection: 'Computer Vision',
      pages: [
        const PaperPage(
          pageNumber: 1,
          sectionTitle: 'Introduction',
          content: 'Deep convolutional neural networks have led to a series of breakthroughs for image classification. Deep networks naturally integrate low/mid/high-level features and classifiers in an end-to-end multi-layer fashion, and the "levels" of features can be enriched by the number of stacked layers (depth). Recent evidence reveals that network depth is of crucial importance, and the leading results on the challenging ImageNet dataset all exploit "very deep" models, with a depth of sixteen to thirty.\n\nDriven by the significance of depth, a question arises: Is learning better networks as easy as stacking more layers? An obstacle to answering this question was the notorious problem of vanishing/exploding gradients, which hamper convergence from the beginning. This problem, however, has been largely addressed by normalized initialization and intermediate normalization layers, which enable networks with tens of layers to start converging for stochastic gradient descent (SGD) with backpropagation.\n\nWhen deeper networks are able to start converging, a degradation problem has been exposed: with the network depth increasing, accuracy gets saturated (which might be unsurprising) and then degrades rapidly. Unexpectedly, such degradation is not caused by overfitting, and adding more layers to a suitably deep model leads to higher training error, as reported in [11, 42] and thoroughly verified by our experiments. The degradation (of training accuracy) indicates that not all systems are similarly easy to optimize.',
        ),
        const PaperPage(
          pageNumber: 2,
          sectionTitle: 'Related Work',
          content: 'Residual Representations. In image recognition, VLAD is a representation that encodes by the residual vectors with respect to a dictionary, and Fisher Vector can be formulated as a probabilistic version of VLAD. Both of them are powerful shallow representations for image retrieval and classification. For vector quantization, encoding residual vectors is shown to be more effective than encoding original vectors. In low-level vision and computer graphics, for solving Partial Differential Equations (PDEs), the widely used Multigrid method reformulates the system as subproblems at multiple scales, where each subproblem is responsible for the residual solution between a coarser and a finer scale.\n\nShortcut Connections. Practices and theories that lead to shortcut connections have been studied for a long time. An early practice of training multi-layer perceptrons (MLPs) is to add a linear layer connected from the network input to the output. In [44, 24], a few intermediate layers are directly connected to auxiliary classifiers for addressing vanishing/exploding gradients. The papers of [39, 38, 31, 47] propose methods for centering layer responses, gradients, and propagated errors, implemented by shortcut connections.\n\nConcurrent to our work, "highway networks" present shortcut connections with gating functions. These gates are data-dependent and have parameters, in contrast to our identity shortcuts that are parameter-free. When a gated shortcut is "closed" (approaching zero), the layers in highway networks represent non-residual functions. On the contrary, our formulation always learns residual functions.',
        ),
        const PaperPage(
          pageNumber: 3,
          sectionTitle: 'Residual Learning',
          content: 'Let us consider H(x) as an underlying mapping to be fit by a few stacked layers (not necessarily the entire net), with x denoting the inputs to the first of these layers. If one hypothesizes that multiple nonlinear layers can asymptotically approximate complicated functions, then it is equivalent to hypothesize that they can asymptotically approximate the residual functions, i.e., H(x) - x (assuming that the input and output are of the same dimensions). So rather than expect stacked layers to approximate H(x), we explicitly let these layers approximate a residual function F(x) := H(x) - x. The original function thus becomes F(x) + x.\n\nAlthough both forms should be able to asymptotically approximate the desired functions (as hypothesized), the ease of learning might be different. This reformulation is motivated by the counterintuitive phenomena about the degradation problem. As we discussed in the introduction, if the added layers can be constructed as identity mappings, a deeper model should have training error no greater than its shallower counterpart. The degradation problem suggests that the solvers might have difficulties in approximating identity mappings by multiple nonlinear layers. With the residual learning reformulation, if identity mappings are optimal, the solvers may simply drive the weights of the multiple nonlinear layers toward zero to approach identity mappings.\n\nIn real cases, it is unlikely that identity mappings are optimal, but our reformulation may help to precondition the problem. If the optimal function is closer to an identity mapping than to a zero mapping, it should be easier for the solver to find the perturbations with reference to an identity mapping, than to learn the function as a new one.',
        ),
        const PaperPage(
          pageNumber: 4,
          sectionTitle: 'Experiments on ImageNet',
          content: 'We evaluate our method on the ImageNet 2012 classification dataset that consists of 1000 classes. The models are trained on the 1.28 million training images, and evaluated on the 50k validation images. We also obtain a final result on the 100k test images, reported by the test server. We evaluate both top-1 and top-5 error rates.\n\nPlain Networks. We first evaluate 18-layer and 34-layer plain nets. The 34-layer plain net is in Figure 3 (middle). Their architecture is based on the VGG nets. We observe that the 34-layer plain net has higher training error throughout the whole training procedure, even though the solution space of the 18-layer plain network is a subspace of that of the 34-layer one. These results reveal the degradation problem.\n\nResidual Networks. Next we evaluate 18-layer and 34-layer residual nets (ResNets). The baseline architectures are the same as the plain nets, except that a shortcut connection is added to each pair of 3x3 filters as in Figure 3 (right). We observe that the situation is reversed with residual learning - the 34-layer ResNet is better than the 18-layer ResNet (by 2.8%). More importantly, the 34-layer ResNet exhibits considerably lower training error and is generalizable to the validation data. This indicates that the degradation problem is well addressed in this setting and we manage to obtain accuracy gains from increased depth.',
        ),
        const PaperPage(
          pageNumber: 5,
          sectionTitle: 'Analysis',
          content: 'To further understand the behavior of residual networks, we introduce deeper variants. For ImageNet, we use a bottleneck architecture for networks of 50 layers or more. Because of concerns on the training time that we can afford, we modify the building block as a bottleneck design. For each residual function F, we use a stack of 3 layers instead of 2. The three layers are 1x1, 3x3, and 1x1 convolutions, where the 1x1 layers are responsible for reducing and then increasing (restoring) dimensions, leaving the 3x3 layer a bottleneck with smaller input/output dimensions.\n\nWe train a 152-layer ResNet on ImageNet. Despite having significantly increased depth, the 152-layer ResNet still has lower complexity than VGG-16/19 nets. The 152-layer ResNet has a top-5 validation error of 4.49%. An ensemble of 6 models gives an error of 3.57% on the test set, winning the 1st place in ILSVRC 2015.\n\nWe have also analyzed the responses of layers. We investigate the standard deviations of the layer responses. The responses are the outputs of a 3x3 layer, after BN and before nonlinearity (ReLU/addition). For ResNets, this analysis reveals the response strength of the residual functions. We observe that ResNets generally have smaller responses than their plain counterparts. These results support our basic motivation that the residual functions might be generally closer to zero than the non-residual functions. We also notice that the deeper ResNet has smaller magnitudes of responses, suggesting that deeper networks tend to have less variations to the input.',
        ),
      ],
    ),
    Paper(
      id: 'bert',
      title: 'BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding',
      authors: ['Jacob Devlin', 'Ming-Wei Chang', 'Kenton Lee', 'Kristina Toutanova'],
      year: 2018,
      abstractText: 'We introduce a new language representation model called BERT, which stands for Bidirectional Encoder Representations from Transformers. Unlike recent language representation models, BERT is designed to pre-train deep bidirectional representations from unlabeled text by jointly conditioning on both left and right context in all layers.',
      tags: ['NLP', 'Pre-training'],
      collection: 'Deep Learning',
      pages: [
        const PaperPage(
          pageNumber: 1,
          sectionTitle: 'Introduction',
          content: 'Language model pre-training has been shown to be effective for improving many natural language processing tasks. These include sentence-level tasks such as natural language inference and paraphrasing, which aim to predict the relationships between sentences by analyzing them holistically, as well as token-level tasks such as named entity recognition and question answering, where models are required to produce fine-grained output at the token level.\n\nThere are two existing strategies for applying pre-trained language representations to downstream tasks: feature-based and fine-tuning. The feature-based approach, such as ELMo, uses task-specific architectures that include the pre-trained representations as additional features. The fine-tuning approach, such as the Generative Pre-trained Transformer (OpenAI GPT), introduces minimal task-specific parameters, and is trained on the downstream tasks by simply fine-tuning all pretrained parameters. The two approaches share the same objective function during pre-training, where they use unidirectional language models to learn general language representations.\n\nWe argue that current techniques restrict the power of the pre-trained representations, especially for the fine-tuning approaches. The major limitation is that standard language models are unidirectional, and this limits the choice of architectures that can be used during pre-training. For example, in OpenAI GPT, the authors use a left-to-right architecture, where every token can only attend to previous tokens in the self-attention layers of the Transformer. Such restrictions are sub-optimal for sentence-level tasks, and could be very harmful when applying fine-tuning based approaches to token-level tasks such as question answering, where it is crucial to incorporate context from both directions.',
        ),
        const PaperPage(
          pageNumber: 2,
          sectionTitle: 'Related Work',
          content: 'Unsupervised Feature-based Approaches. Learning widely applicable representations of words has been an active area of research for decades, including non-neural and neural methods. Pre-trained word embeddings are an integral part of modern NLP systems, offering significant improvements over embeddings learned from scratch. To pre-train word embedding vectors, left-to-right language modeling objectives have been used, as well as objectives to discriminate correct from incorrect words in left and right context.\n\nUnsupervised Fine-tuning Approaches. As with the feature-based approaches, the first works in this direction only pre-trained word embedding parameters from unlabeled text. More recently, sentence or document encoders which produce contextual token representations have been pre-trained from unlabeled text and fine-tuned for a supervised downstream task. The advantage of these approaches is that few parameters need to be learned from scratch. At least partly due to this advantage, OpenAI GPT achieved previously state-of-the-art results on many sentence-level tasks from the GLUE benchmark.\n\nTransfer Learning from Supervised Data. There has also been work showing effective transfer from supervised tasks with large datasets, such as natural language inference and machine translation. Computer vision research has also demonstrated the importance of transfer learning from large pre-trained models, where an effective recipe is to fine-tune models pre-trained with ImageNet.',
        ),
        const PaperPage(
          pageNumber: 3,
          sectionTitle: 'BERT Model',
          content: 'The BERT framework introduces a unified architecture across different tasks. There is minimal difference between the pre-trained architecture and the final downstream architecture. Model Architecture: BERT\'s model architecture is a multi-layer bidirectional Transformer encoder based on the original implementation described in Vaswani et al. and released in the tensor2tensor library. Because the use of Transformers has become common and our implementation is almost identical to the original, we omit an exhaustive background description of the model architecture.\n\nIn this work, we denote the number of layers (i.e., Transformer blocks) as L, the hidden size as H, and the number of self-attention heads as A. We primarily report results on two model sizes: BERT_BASE (L=12, H=768, A=12, Total Parameters=110M) and BERT_LARGE (L=24, H=1024, A=16, Total Parameters=340M). BERT_BASE was chosen to have the same model size as OpenAI GPT for comparison purposes. However, critically, the BERT Transformer uses bidirectional self-attention, while the GPT Transformer uses constrained self-attention where every token can only attend to context to its left.\n\nInput/Output Representations: To make BERT handle a variety of down-stream tasks, our input representation is able to unambiguously represent both a single sentence and a pair of sentences (e.g., <Question, Answer>) in one token sequence. Throughout this work, a "sentence" can be an arbitrary span of contiguous text, rather than an actual linguistic sentence. A "sequence" refers to the input token sequence to BERT, which may be a single sentence or two sentences packed together. We use WordPiece embeddings with a 30,000 token vocabulary.',
        ),
        const PaperPage(
          pageNumber: 4,
          sectionTitle: 'Pre-training Tasks',
          content: 'Unlike Peters et al. and Radford et al., we do not use traditional left-to-right or right-to-left language models to pre-train BERT. Instead, we pre-train BERT using two unsupervised tasks. Task 1: Masked LM (MLM). Intuitively, it is reasonable to believe that a deep bidirectional model is strictly more powerful than either a left-to-right model or the shallow concatenation of a left-to-right and a right-to-left model. Unfortunately, standard conditional language models can only be trained left-to-right or right-to-left, since bidirectional conditioning would allow each word to indirectly "see itself", and the model could trivially predict the target word in a multi-layered context.\n\nIn order to train a deep bidirectional representation, we simply mask some percentage of the input tokens at random, and then predict those masked tokens. We refer to this procedure as a "masked LM" (MLM), although it is often referred to as a Cloze task in the literature. In this case, the final hidden vectors corresponding to the mask tokens are fed into an output softmax over the vocabulary, as in a standard LM. In all of our experiments, we mask 15% of all WordPiece tokens in each sequence at random.\n\nTask 2: Next Sentence Prediction (NSP). Many important downstream tasks such as Question Answering (QA) and Natural Language Inference (NLI) are based on understanding the relationship between two sentences, which is not directly captured by language modeling. In order to train a model that understands sentence relationships, we pre-train for a binarized next sentence prediction task that can be trivially generated from any monolingual corpus. Specifically, when choosing the sentences A and B for each pretraining example, 50% of the time B is the actual next sentence that follows A (labeled as IsNext), and 50% of the time it is a random sentence from the corpus (labeled as NotNext).',
        ),
        const PaperPage(
          pageNumber: 5,
          sectionTitle: 'Fine-tuning and Results',
          content: 'Fine-tuning is straightforward since the self-attention mechanism in the Transformer allows BERT to model many downstream tasks—whether they involve single text or text pairs—by swapping out the appropriate inputs and outputs. For applications involving text pairs, a common pattern is to independently encode text pairs before applying bidirectional cross attention, such as Parikh et al. and Seo et al. BERT instead uses the self-attention mechanism to unify these two stages, as encoding a concatenated text pair with self-attention effectively includes bidirectional cross attention between two sentences.\n\nFor each task, we simply plug in the task-specific inputs and outputs into BERT and fine-tune all the parameters end-to-end. At the input, sentence A and sentence B from pre-training are analogous to (1) sentence pairs in paraphrasing, (2) hypothesis-premise pairs in entailment, (3) question-passage pairs in question answering, and (4) a degenerate text-∅ pair in text classification or sequence tagging.\n\nOn the GLUE benchmark, BERT_LARGE achieves a score of 80.5%, compared to OpenAI GPT\'s 72.8%. BERT consistently outperforms previous state-of-the-art models on all tasks. On SQuAD v1.1, the BERT_LARGE ensemble achieves an F1 score of 93.2, outperforming the previous top system by 1.5 points. These results demonstrate the empirical superiority of bidirectional pre-training for language representations.',
        ),
      ],
    ),
    Paper(
      id: 'diffusion',
      title: 'Denoising Diffusion Probabilistic Models',
      authors: ['Jonathan Ho', 'Ajay Jain', 'Pieter Abbeel'],
      year: 2020,
      abstractText: 'We present high quality image synthesis results using diffusion probabilistic models, a class of latent variable models inspired by considerations from nonequilibrium thermodynamics. Our best results are obtained by training on a weighted variational bound designed according to a novel connection between diffusion probabilistic models and denoising score matching with Langevin dynamics.',
      tags: ['Generative', 'Diffusion'],
      collection: 'Generative Models',
      pages: [
        const PaperPage(
          pageNumber: 1,
          sectionTitle: 'Introduction',
          content: 'Deep generative models of several kinds have recently exhibited high quality samples in a wide variety of data modalities. Generative adversarial networks (GANs), autoregressive models, flows, and variational autoencoders (VAEs) have seen striking successes. Each framework has tradeoffs: GANs are known for high quality samples but can be difficult to train and suffer from mode collapse. Likelihood-based models like VAEs and flows are easier to train but often produce lower quality, blurry samples.\n\nIn this paper, we present progress on diffusion probabilistic models. A diffusion probabilistic model (which we will call a "diffusion model" for brevity) is a parameterized Markov chain trained using variational inference to produce samples matching the data after finite time. Transitions of this chain are learned to reverse a diffusion process, which is a Markov chain that gradually adds noise to the data in the opposite direction of sampling until signal is destroyed.\n\nDiffusion models are straightforward to define and efficient to train, but to the best of our knowledge, there has been no demonstration that they are capable of generating high quality samples. We show that diffusion models actually are capable of generating high quality samples, sometimes better than the published state-of-the-art results on certain datasets. In addition, we show that a certain parameterization of diffusion models reveals an equivalence with denoising score matching over multiple noise levels during training and with annealed Langevin dynamics during sampling.',
        ),
        const PaperPage(
          pageNumber: 2,
          sectionTitle: 'Diffusion Models',
          content: 'A diffusion model is a latent variable model of the form p_theta(x_0) = int p_theta(x_0:T) dx_1:T, where x_1, ..., x_T are latents of the same dimensionality as the data x_0. The joint distribution p_theta(x_0:T) is called the reverse process, and it is defined as a Markov chain with learned Gaussian transitions starting at p(x_T) = N(x_T; 0, I). The transitions are parameterized as p_theta(x_{t-1} | x_t) = N(x_{t-1}; mu_theta(x_t, t), Sigma_theta(x_t, t)).\n\nWhat distinguishes diffusion models from other types of latent variable models is that the approximate posterior q(x_1:T | x_0), called the forward process or diffusion process, is fixed to a Markov chain that gradually adds Gaussian noise to the data according to a variance schedule beta_1, ..., beta_T. The forward process transitions are q(x_t | x_{t-1}) = N(x_t; sqrt(1 - beta_t) x_{t-1}, beta_t I).\n\nTraining is performed by optimizing the usual variational bound on negative log likelihood. By rewriting the variational bound in terms of Kullback-Leibler divergences, one can see that learning the reverse process transitions amounts to training neural networks to predict the parameters of the posterior transitions of the forward process. Under the assumption that the forward process variances beta_t are small, the reverse process transitions can be parameterized as Gaussians, and their parameters can be trained to match the intractable true posterior by minimizing the KL divergences.',
        ),
        const PaperPage(
          pageNumber: 3,
          sectionTitle: 'Forward and Reverse Process',
          content: 'To formulate our training objective, we need to parameterize the reverse process p_theta(x_{t-1} | x_t) and choose the variance schedule for the forward process. For the reverse process, we set the variance to time-dependent constants and parameterize the mean using a neural network. Specifically, instead of predicting the mean directly, we parameterize the neural network to predict the added noise epsilon. This parameterization is motivated by a connection to denoising score matching.\n\nThe resulting training objective is beautifully simple: we sample a data point x_0, a time step t uniformly between 1 and T, and a noise vector epsilon. We corrupt x_0 by adding the noise epsilon scaled appropriately for time t to obtain x_t. Then, we train the neural network epsilon_theta to predict the noise epsilon given x_t and t. The loss is simply the mean squared error between the true noise and the predicted noise.\n\nFor sampling, we start with pure Gaussian noise x_T and iteratively sample x_{t-1} from p_theta(x_{t-1} | x_t) until we reach x_0. This process is equivalent to annealed Langevin dynamics, where the neural network provides an estimate of the score (the gradient of the log data density) at each noise level. We employ a U-Net architecture based on Wide ResNet for the neural network, which incorporates self-attention blocks and sinusoidal position embeddings to condition on the time step t.',
        ),
        const PaperPage(
          pageNumber: 4,
          sectionTitle: 'Experiments',
          content: 'We evaluate our models on CIFAR10, LSUN, and CelebA-HQ datasets. For all experiments, we set T = 1000 and use a linear variance schedule for the forward process. Our neural network architecture is a U-Net with ResNet blocks and self-attention, similar to the architecture used in PixelCNN++.\n\nOn CIFAR10, our model achieves an Inception Score of 9.46 and a Frechet Inception Distance (FID) of 3.17, which is highly competitive with state-of-the-art generative models. We found that the simplified training objective, which predicts the noise rather than the mean, yields significantly better sample quality compared to optimizing the exact variational bound.\n\nWe also observe that diffusion models have a compelling inductive bias for images. By analyzing the representations at different time steps during the reverse process, we see that the model generates coarse, low-frequency features early in the process and refines fine details and high-frequency features later. This hierarchical nature allows diffusion models to generate coherent global structures while maintaining high-fidelity local details. Furthermore, the latent space of diffusion models exhibits smooth interpolations, allowing us to traverse the data manifold by interpolating the noise vectors.',
        ),
      ],
    ),
    Paper(
      id: 'dqn',
      title: 'Playing Atari with Deep Reinforcement Learning',
      authors: ['Volodymyr Mnih', 'Koray Kavukcuoglu', 'David Silver', 'Alex Graves'],
      year: 2013,
      abstractText: 'We present the first deep learning model to successfully learn control policies directly from high-dimensional sensory input using reinforcement learning. The model is a convolutional neural network, trained with a variant of Q-learning, whose input is raw pixels and whose output is a value function estimating future rewards.',
      tags: ['RL', 'Deep Learning'],
      collection: 'Reinforcement Learning',
      pages: [
        const PaperPage(
          pageNumber: 1,
          sectionTitle: 'Introduction',
          content: 'Learning to control agents directly from high-dimensional sensory inputs like vision and speech is one of the long-standing challenges of reinforcement learning (RL). Most successful RL applications that operate on these domains have relied on hand-crafted features combined with linear value functions or policy representations. Clearly, the performance of such systems heavily relies on the quality of the feature representation.\n\nRecent advances in deep learning have made it possible to extract high-level features from raw sensory data, leading to breakthroughs in computer vision and speech recognition. These methods utilize a range of neural network architectures, including convolutional networks, multilayer perceptrons, restricted Boltzmann machines and recurrent neural networks, and have exploited both supervised and unsupervised learning. It seems natural to ask whether similar techniques could be beneficial for RL with sensory data.\n\nHowever, reinforcement learning presents several challenges from a deep learning perspective. Firstly, most successful deep learning applications to date have required large amounts of hand-labelled training data. RL algorithms, on the other hand, must be able to learn from a scalar reward signal that is frequently sparse, noisy and delayed. Secondly, most deep learning algorithms assume the data samples to be independent, while in RL one typically encounters sequences of highly correlated states. Furthermore, in RL the data distribution changes as the algorithm learns new behaviours, which can be problematic for deep learning methods that assume a fixed underlying distribution.',
        ),
        const PaperPage(
          pageNumber: 2,
          sectionTitle: 'Background',
          content: 'We consider tasks in which an agent interacts with an environment, in this case the Atari emulator, in a sequence of actions, observations and rewards. At each step the agent selects an action from the set of legal game actions. The action is passed to the emulator and modifies its internal state and the game score. The agent observes an image from the emulator representing the screen pixels.\n\nWe assume that future rewards are discounted by a factor gamma per time-step, and define the future discounted return at time t as R_t = sum_{t\'=t}^T gamma^{t\'-t} r_{t\'}. The goal of the agent is to interact with the emulator by selecting actions in a way that maximizes future reward. We define the optimal action-value function Q*(s, a) as the maximum expected return achievable by following any strategy, after seeing some state s and then taking some action a.\n\nThe optimal action-value function obeys an important identity known as the Bellman equation. This is based on the following intuition: if the optimal value Q*(s\', a\') of the sequence s\' at the next time-step was known for all possible actions a\', then the optimal strategy is to select the action a\' maximizing the expected value of r + gamma Q*(s\', a\'). The basic idea behind many reinforcement learning algorithms is to estimate the action-value function, by using the Bellman equation as an iterative update.',
        ),
        const PaperPage(
          pageNumber: 3,
          sectionTitle: 'Deep Q-Network',
          content: 'We parameterize an approximate value function Q(s, a; theta) using a convolutional neural network, which we refer to as a deep Q-network (DQN). The neural network weights theta are updated by minimizing a sequence of loss functions L_i(theta_i) that changes at each iteration i. The loss function is the mean squared error between the target Q-value (computed using the previous network weights) and the predicted Q-value.\n\nTo alleviate the problems of correlated data and non-stationary distributions, we use a technique known as experience replay. We store the agent\'s experiences e_t = (s_t, a_t, r_t, s_{t+1}) at each time-step t in a data set D = {e_1, ..., e_N}, pooled over many episodes into a replay memory. During the inner loop of the algorithm, we apply Q-learning updates, or minibatch updates, to samples of experience e ~ D, drawn at random from the pool of stored samples.\n\nThis approach has several advantages over standard online Q-learning. First, each step of experience is potentially used in many weight updates, which allows for greater data efficiency. Second, learning directly from consecutive samples is inefficient, due to the strong correlations between the samples; randomizing the samples breaks these correlations and therefore reduces the variance of the updates. Third, when learning on-policy the current parameters determine the next data sample that the parameters are trained on. By using experience replay the behavior distribution is averaged over many of its previous states, smoothing out learning and avoiding oscillations or divergence in the parameters.',
        ),
        const PaperPage(
          pageNumber: 4,
          sectionTitle: 'Experiments and Results',
          content: 'We evaluated our approach on a set of seven popular Atari 2600 games. We used the same network architecture, learning algorithm and hyperparameters across all seven games, showing that our approach is robust enough to work on a variety of games without incorporating game-specific information. The input to the neural network consists of an 84x84x4 image produced by the preprocessing function phi, representing the last 4 frames of the game.\n\nOur Deep Q-Network outperforms all previous approaches on six of the seven games we tested and surpasses a human expert on three of them. On games like Breakout, Enduro, and Pong, the DQN agent learned to play the games exceptionally well. In Breakout, the agent even discovered the optimal strategy of digging a tunnel through the wall and bouncing the ball behind it, a strategy that is not obvious to a beginner human player.\n\nThe results demonstrate that a single architecture can learn successful control policies across a range of different environments with only raw pixels and a scalar reward signal as inputs. The combination of deep convolutional neural networks with Q-learning and experience replay proved to be a critical factor in stabilizing the learning process and achieving human-level performance on complex tasks.',
        ),
      ],
    ),
  ];
}
